# Generated by Django 3.0.11 on 2020-12-21 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201221_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 16, 48, 33, 631007, tzinfo=utc)),
        ),
    ]
